COINS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "XRPUSDT", "ADAUSDT",
    "SOLUSDT", "DOGEUSDT", "MATICUSDT", "DOTUSDT", "AVAXUSDT",
    "LINKUSDT", "LTCUSDT", "TRXUSDT", "ETCUSDT", "BCHUSDT",
    "UNIUSDT", "AAVEUSDT", "FILUSDT", "ATOMUSDT", "NEARUSDT",
    "FTMUSDT", "ICPUSDT", "INJUSDT", "RNDRUSDT", "GRTUSDT",
    "OPUSDT", "ARBUSDT", "SHIBUSDT", "APTUSDT", "SANDUSDT",
    "MANAUSDT", "EGLDUSDT"
]
